version: "2"

# Forward all Docker logging to the local_services Logstash
services:

  web:
    build:
      args:
        # FIXME: These should be the args used, but until Docker 1.13 is released with the enhancement at <https://github.com/docker/docker/pull/27702>, the build container cannot talk to the local-services IPs, as it wonâ€™t be on the same network.  Once that enhancement gets released, there should be a way to specify the network used for the build container here in Compose, perhaps with a `network` key within the `build` section.  For now, wire the Docker host IP address, as the port is published there anyway.
        PIP_INDEX_URL: "http://172.17.0.1:3141/root/pypi/+simple/"
        PIP_TRUSTED_HOST: "172.17.0.1"
        # PIP_INDEX_URL: "http://devpi-local-3141.service.consul.test:3141/simple/"
        # PIP_TRUSTED_HOST: "devpi-local-3141.service.consul.test:3141"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash-local-12201.service.consul.test:12201"

  logstash:
    environment:
      # Make this project's Logstash write to the local_services Elasticsearch
      ELASTICSEARCH_HOST: "elasticsearch-local-9200.service.consul.test"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash-local-12201.service.consul.test:12201"

  postgres:
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash-local-12201.service.consul.test:12201"

  elasticsearch:
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash-local-12201.service.consul.test:12201"

  # Disable this project's Kibana in favor of the one from local_services
  kibana:
    entrypoint: "true"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash-local-12201.service.consul.test:12201"
    restart: "no"

networks:
  default:
    external:
      name: "localservices_default"
